// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTrungTamLapTrinh.Data;

#nullable disable

namespace QuanLyTrungTamLapTrinh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.DanhSachDangKy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HocVien_Id")
                        .HasColumnType("int");

                    b.Property<int>("LichKhaiGiang_Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HocVien_Id");

                    b.HasIndex("LichKhaiGiang_Id");

                    b.ToTable("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.DanhSachThietBi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PhongHoc_Id")
                        .HasColumnType("int");

                    b.Property<int>("SL")
                        .HasColumnType("int");

                    b.Property<int>("ThietBi_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongHoc_Id");

                    b.HasIndex("ThietBi_Id");

                    b.ToTable("DanhSachThietBi");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.GiaoVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChuyenMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Luong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GiaoVien");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DanhSachDangKy_Id")
                        .HasColumnType("int");

                    b.Property<int?>("GiamGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoTien")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DanhSachDangKy_Id");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.HocVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoCCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HocPhi")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.KhoaKhaiGiang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KhoaKhaiGiang");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.LichKhaiGiang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaoVien_Id")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHoc_Id")
                        .HasColumnType("int");

                    b.Property<int>("KhoaKhaiGiang_Id")
                        .HasColumnType("int");

                    b.Property<string>("NgayHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nhom")
                        .HasColumnType("int");

                    b.Property<int>("PhongHoc_Id")
                        .HasColumnType("int");

                    b.Property<int>("SoBuoiHoc")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongDK")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GiaoVien_Id");

                    b.HasIndex("KhoaHoc_Id");

                    b.HasIndex("KhoaKhaiGiang_Id");

                    b.HasIndex("Nhom");

                    b.ToTable("LichKhaiGiang");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.PhongHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhongHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.ThietBi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThietBi");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.ThietBiHuHong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTaLoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayPhatHien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySuaChua")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhongHoc_Id")
                        .HasColumnType("int");

                    b.Property<int>("ThietBi_Id")
                        .HasColumnType("int");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ViTri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhongHoc_Id");

                    b.HasIndex("ThietBi_Id");

                    b.ToTable("ThietBiHuHong");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.DanhSachDangKy", b =>
                {
                    b.HasOne("QuanLyTrungTamLapTrinh.Models.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVien_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamLapTrinh.Models.LichKhaiGiang", "LichKhaiGiang")
                        .WithMany("DanhSachDangKy")
                        .HasForeignKey("LichKhaiGiang_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LichKhaiGiang");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.DanhSachThietBi", b =>
                {
                    b.HasOne("QuanLyTrungTamLapTrinh.Models.PhongHoc", "PhongHoc")
                        .WithMany("DanhSachThietBi")
                        .HasForeignKey("PhongHoc_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamLapTrinh.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("ThietBi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongHoc");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.HoaDon", b =>
                {
                    b.HasOne("QuanLyTrungTamLapTrinh.Models.DanhSachDangKy", "DanhSachDangKy")
                        .WithMany()
                        .HasForeignKey("DanhSachDangKy_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.LichKhaiGiang", b =>
                {
                    b.HasOne("QuanLyTrungTamLapTrinh.Models.GiaoVien", "GiaoVien")
                        .WithMany("LichKhaiGiang")
                        .HasForeignKey("GiaoVien_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamLapTrinh.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHoc_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamLapTrinh.Models.KhoaKhaiGiang", "KhoaKhaiGiang")
                        .WithMany("LichKhaiGiang")
                        .HasForeignKey("KhoaKhaiGiang_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamLapTrinh.Models.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("Nhom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("KhoaKhaiGiang");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.ThietBiHuHong", b =>
                {
                    b.HasOne("QuanLyTrungTamLapTrinh.Models.PhongHoc", "PhongHoc")
                        .WithMany("ThietBiHuHong")
                        .HasForeignKey("PhongHoc_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTrungTamLapTrinh.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("ThietBi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongHoc");

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.GiaoVien", b =>
                {
                    b.Navigation("LichKhaiGiang");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.KhoaKhaiGiang", b =>
                {
                    b.Navigation("LichKhaiGiang");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.LichKhaiGiang", b =>
                {
                    b.Navigation("DanhSachDangKy");
                });

            modelBuilder.Entity("QuanLyTrungTamLapTrinh.Models.PhongHoc", b =>
                {
                    b.Navigation("DanhSachThietBi");

                    b.Navigation("ThietBiHuHong");
                });
#pragma warning restore 612, 618
        }
    }
}
